import { useLocation, Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { Footer } from "@/components/Footer";

const content = {
  "pt-BR": {
    title: "Política de Privacidade",
    lastUpdated: "Última atualização: Fevereiro de 2025",
    backLink: "/",
    backText: "Voltar",
    sections: [
      {
        title: "1. Introdução",
        content: `A DROP Edit ("nós", "nosso" ou "plataforma") respeita sua privacidade e está comprometida em proteger seus dados pessoais. Esta Política de Privacidade explica como coletamos, usamos e protegemos suas informações quando você utiliza nosso serviço de leitura estética editorial.`
      },
      {
        title: "2. Dados que Coletamos",
        content: `**Imagens enviadas:** As imagens de referência que você envia são processadas temporariamente por inteligência artificial para gerar sua leitura estética. **Não armazenamos suas imagens** — elas são descartadas imediatamente após o processamento.

**Resultados gerados:** Os textos editoriais gerados pela IA são armazenados localmente no seu dispositivo (localStorage) para que você possa acessá-los posteriormente. Mantemos apenas os últimos 5 resultados.

**Dados de uso:** Coletamos informações anônimas sobre como você interage com a plataforma (páginas visitadas, tempo de uso, tipo de dispositivo) para melhorar nosso serviço.`
      },
      {
        title: "3. Cookies e Análise",
        content: `Utilizamos cookies exclusivamente para fins de análise de tráfego através do Google Analytics. Estes cookies nos ajudam a entender como os visitantes usam nossa plataforma.

Você pode aceitar ou recusar cookies através do banner de consentimento exibido na primeira visita. Mesmo que recuse, você poderá usar todas as funcionalidades da plataforma normalmente.`
      },
      {
        title: "4. Como Usamos seus Dados",
        content: `Utilizamos os dados coletados para:
• Processar suas imagens e gerar leituras estéticas personalizadas
• Melhorar a qualidade e precisão do nosso serviço de IA
• Analisar tendências de uso para aprimorar a experiência do usuário
• Comunicar atualizações importantes sobre o serviço`
      },
      {
        title: "5. Compartilhamento de Dados",
        content: `Não vendemos, alugamos ou compartilhamos seus dados pessoais com terceiros para fins de marketing. Podemos compartilhar dados anonimizados com:
• Provedores de serviços de análise (Google Analytics)
• Provedores de infraestrutura de nuvem para processamento de IA

Todos os nossos parceiros estão sujeitos a acordos de confidencialidade.`
      },
      {
        title: "6. Seus Direitos (LGPD)",
        content: `De acordo com a Lei Geral de Proteção de Dados (LGPD), você tem direito a:
• Confirmar a existência de tratamento de dados
• Acessar seus dados
• Corrigir dados incompletos ou desatualizados
• Solicitar anonimização ou exclusão de dados desnecessários
• Revogar consentimento a qualquer momento
• Obter informações sobre compartilhamento de dados

Para exercer qualquer destes direitos, entre em contato conosco.`
      },
      {
        title: "7. Segurança",
        content: `Implementamos medidas técnicas e organizacionais apropriadas para proteger seus dados contra acesso não autorizado, alteração, divulgação ou destruição. Utilizamos criptografia em trânsito (HTTPS) e processamento seguro em nuvem.`
      },
      {
        title: "8. Alterações nesta Política",
        content: `Podemos atualizar esta Política de Privacidade periodicamente. Notificaremos você sobre mudanças significativas através de aviso na plataforma. O uso continuado do serviço após as alterações constitui aceitação da nova política.`
      },
      {
        title: "9. Contato",
        content: `Para dúvidas, solicitações ou reclamações relacionadas à privacidade, entre em contato:

**E-mail:** contato@dropedit.com.br`
      }
    ]
  },
  en: {
    title: "Privacy Policy",
    lastUpdated: "Last updated: February 2025",
    backLink: "/global",
    backText: "Back",
    sections: [
      {
        title: "1. Introduction",
        content: `DROP Edit ("we", "our", or "platform") respects your privacy and is committed to protecting your personal data. This Privacy Policy explains how we collect, use, and protect your information when you use our editorial style reading service.`
      },
      {
        title: "2. Data We Collect",
        content: `**Uploaded images:** The reference images you submit are temporarily processed by artificial intelligence to generate your style reading. **We do not store your images** — they are discarded immediately after processing.

**Generated results:** The editorial texts generated by AI are stored locally on your device (localStorage) so you can access them later. We only keep the last 5 results.

**Usage data:** We collect anonymous information about how you interact with the platform (pages visited, time spent, device type) to improve our service.`
      },
      {
        title: "3. Cookies and Analytics",
        content: `We use cookies exclusively for traffic analysis purposes through Google Analytics. These cookies help us understand how visitors use our platform.

You can accept or decline cookies through the consent banner displayed on your first visit. Even if you decline, you will be able to use all platform features normally.`
      },
      {
        title: "4. How We Use Your Data",
        content: `We use the collected data to:
• Process your images and generate personalized style readings
• Improve the quality and accuracy of our AI service
• Analyze usage trends to enhance user experience
• Communicate important service updates`
      },
      {
        title: "5. Data Sharing",
        content: `We do not sell, rent, or share your personal data with third parties for marketing purposes. We may share anonymized data with:
• Analytics service providers (Google Analytics)
• Cloud infrastructure providers for AI processing

All our partners are subject to confidentiality agreements.`
      },
      {
        title: "6. Your Rights (LGPD/GDPR)",
        content: `In accordance with applicable data protection laws (LGPD/GDPR), you have the right to:
• Confirm the existence of data processing
• Access your data
• Correct incomplete or outdated data
• Request anonymization or deletion of unnecessary data
• Revoke consent at any time
• Obtain information about data sharing

To exercise any of these rights, please contact us.`
      },
      {
        title: "7. Security",
        content: `We implement appropriate technical and organizational measures to protect your data against unauthorized access, alteration, disclosure, or destruction. We use encryption in transit (HTTPS) and secure cloud processing.`
      },
      {
        title: "8. Changes to This Policy",
        content: `We may update this Privacy Policy periodically. We will notify you of significant changes through a notice on the platform. Continued use of the service after changes constitutes acceptance of the new policy.`
      },
      {
        title: "9. Contact",
        content: `For questions, requests, or complaints related to privacy, please contact:

**Email:** contato@dropedit.com.br`
      }
    ]
  }
};

function parseMarkdown(text: string) {
  return text.split('\n').map((line, i) => {
    // Bold text
    const parts = line.split(/(\*\*[^*]+\*\*)/g);
    const rendered = parts.map((part, j) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return <strong key={j} className="font-medium text-foreground">{part.slice(2, -2)}</strong>;
      }
      return part;
    });
    
    // Bullet points
    if (line.startsWith('• ')) {
      return <li key={i} className="ml-4">{rendered}</li>;
    }
    
    return <p key={i} className={line === '' ? 'h-4' : ''}>{rendered}</p>;
  });
}

export default function PrivacyPolicyPage() {
  const location = useLocation();
  const isGlobalRoute = location.pathname.startsWith("/global");
  const locale = isGlobalRoute ? "en" : "pt-BR";
  const t = content[locale];

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <div className="flex-1 px-4 py-8 md:py-16">
        <div className="max-w-2xl mx-auto">
          <Link 
            to={t.backLink}
            className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors mb-8"
          >
            <ArrowLeft className="w-4 h-4" />
            {t.backText}
          </Link>

          <header className="mb-12">
            <h1 className="editorial-headline text-3xl md:text-4xl mb-3">
              {t.title}
            </h1>
            <p className="text-sm text-muted-foreground">
              {t.lastUpdated}
            </p>
          </header>

          <div className="space-y-8">
            {t.sections.map((section, index) => (
              <section key={index} className="space-y-3">
                <h2 className="font-serif text-lg font-medium text-foreground">
                  {section.title}
                </h2>
                <div className="editorial-body text-sm text-muted-foreground leading-relaxed space-y-2">
                  {parseMarkdown(section.content)}
                </div>
              </section>
            ))}
          </div>
        </div>
      </div>
      
      <Footer locale={locale} />
    </div>
  );
}
